### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by DhairyaBahl** [DhairyaBahl/React-Calculator#1]
### Description

Although this is a web application but still it is created with mobile view in mind. So this app works great in the mobile browser but have wrong alignment in the pc browsers

### Solution

CSS is hard coded specifically for mobile. Make it responsive by using media queries.

**Comment by Doringl** [comment]
Hello, i can help you if you want ?

**Comment by DhairyaBahl** [comment]
@Doringl Ofcourse Go Ahead !!

**Comment by Doringl** [comment]
Sorry I'm a little late but  i created a pull request.
